http:
  enabled: false
input:
  label: ""
  redis_streams:
    url: ${REDIS_URL:redis://host.docker.internal:6379}
    body_key: body
    streams:
      - benthos_stream
    limit: 10
    client_id: benthos_consumer
    consumer_group: benthos_group
buffer:
  none: {}
pipeline:
  threads: 1
  processors: []
output:
  label: ""
  stdout:
    codec: lines
logger:
  level: INFO
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
tracer:
  none: {}
shutdown_timeout: 20s
